version: '2.1'

networks:
  bibbox-default-network:
    external: true

services:
  §§INSTANCE-galaxy:
    image: bgruening/galaxy-stable:latest # §§
    container_name: §§INSTANCE-galaxy
    networks:
        - bibbox-default-network
    volumes_from:
      - §§INSTANCE-galaxy-data
    expose:
        - 80
    ports:
        - "§§PORT4:80"
    restart: on-failure

  §§INSTANCE-galaxy-data:
    image: quay.io/bgruening/galaxy-init:${GALAXY_DOCKER_TAG:-latest}
    container_name: §§INSTANCE-galaxy-data
    volumes:
      - data/galaxy-storage:/export
